# Generated by Django 5.1.1 on 2024-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "places",
                    models.SmallIntegerField(
                        default=2,
                        help_text="Введите число бронируемых мест",
                        verbose_name="Число бронируемых мест",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите примечания к бронированию",
                        null=True,
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "notification",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Не оповещать"),
                            (1, "За час"),
                            (2, "За два часа"),
                            (3, "За три часа"),
                        ],
                        default=0,
                        verbose_name="Оповещение на Telegram (если указан при регистрации)",
                    ),
                ),
                (
                    "date_field",
                    models.DateField(
                        help_text="введите дата бронирования",
                        verbose_name="дата бронирования",
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        help_text="введите начало бронирования",
                        verbose_name="начало бронирования",
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        help_text="введите конец бронирования",
                        verbose_name="конец бронирования",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="введите активно ли бронирование",
                        verbose_name="активно ли бронирование",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания бронирования",
                        verbose_name="дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронирования",
            },
        ),
        migrations.CreateModel(
            name="BookingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания токена",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название картинки",
                        max_length=150,
                        unique=True,
                        verbose_name="картинка-название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание картинки",
                        null=True,
                        verbose_name="Описание картинки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="content/photo",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "картинка",
                "verbose_name_plural": "картинки",
            },
        ),
        migrations.CreateModel(
            name="Contentlink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название ссылки",
                        max_length=50,
                        unique=True,
                        verbose_name="название ссылки",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="введите текст ссылки",
                        max_length=50,
                        unique=True,
                        verbose_name="текст ссылки",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="введите адрес ссылки",
                        max_length=150,
                        verbose_name="адрес ссылки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание ссылки",
                        verbose_name="описание ссылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
            },
        ),
        migrations.CreateModel(
            name="ContentParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название параметра",
                        max_length=50,
                        unique=True,
                        verbose_name="название параметра",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        help_text="введите значение параметра",
                        max_length=150,
                        verbose_name="значение параметра",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание параметра",
                        verbose_name="описание параметра",
                    ),
                ),
            ],
            options={
                "verbose_name": "параметр",
                "verbose_name_plural": "параметры",
            },
        ),
        migrations.CreateModel(
            name="ContentText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название текстового блока",
                        max_length=150,
                        unique=True,
                        verbose_name="контент-название",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="введите тело текстового блока",
                        verbose_name="тело текстового блока",
                    ),
                ),
            ],
            options={
                "verbose_name": "контент",
                "verbose_name_plural": "контент",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Введите текст вопроса", verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "sign",
                    models.CharField(
                        help_text="Введите подпись под вопросом",
                        max_length=50,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак проверки",
                        verbose_name="Проверен",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ на вопрос",
                        null=True,
                        verbose_name="Ответ на вопрос",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания",
                        verbose_name="дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Введите текст отзыва", verbose_name="Текст отзыва"
                    ),
                ),
                (
                    "sign",
                    models.CharField(
                        help_text="Введите подпись под отзывом",
                        max_length=50,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Не оповещать"),
                            (1, "За час"),
                            (2, "За два часа"),
                            (3, "За три часа"),
                        ],
                        default=5,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак проверки",
                        verbose_name="Проверен",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ на отзыв",
                        null=True,
                        verbose_name="Ответ на отзыв",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="введите дату изменения",
                        verbose_name="дата изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.SmallIntegerField(
                        help_text="Введите номер столика",
                        unique=True,
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "places",
                    models.SmallIntegerField(
                        default=4,
                        help_text="Введите число сидячих мест у столика",
                        verbose_name="Число сидячих мест у столика",
                    ),
                ),
                (
                    "flour",
                    models.SmallIntegerField(
                        default=1,
                        help_text="Введите этаж нахождения столика",
                        verbose_name="Этаж нахождения столика",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="обычный столик",
                        help_text="Введите описание столика",
                        verbose_name="Описание столика",
                    ),
                ),
            ],
            options={
                "verbose_name": "столик",
                "verbose_name_plural": "столики",
            },
        ),
    ]
