# Generated by Django 5.1.1 on 2024-10-25 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="пользователь",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="bookingtoken",
            name="booking",
            field=models.ForeignKey(
                help_text="токен для восстановления пароля",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_token",
                to="restaurant.booking",
                verbose_name="бронирование",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="пользователь",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                help_text="выберите столик",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="restaurant.table",
                verbose_name="столик",
            ),
        ),
    ]
